### ISSUE TITLE
Fit to screen

### ISSUE THREAD

**Issue by MadalinaDrulea** [px2code/Figma-to-HTML#3]
Hello, I am trying to make my Figma pages responsive on different devices (laptop, extra screen, etc) and I was able to fit the page on my screen so there is no scrolling involved, but on my laptop the components on the page cut off (so the scrolling doesn't happen) because the resolution is smaller than on the screen.

What I did: 
- I added where it says Font Setting at the top of the project the following line in the CSS Font Face category:
body {
    overflow: hidden;
};

- I added in the div block, under style - custom style:
 background-size: cover.

Also, I have pages in my project which should function as pop-ups, so they would need to be smaller than the screen they are presented on and at this moment they fit the screen, do you know how I can adjust the dimensions of each pop-up?

Thank you!

**Comment by px2code** [comment]
I am not sure if I understand your question correctly, but please let me know if I don't answer your question.

It seems you want the component to fit the screen height, right?

In the HTML world, the content would be scrollable vertically by default.
If you want the component to fit height, you need to enable the option **Fit Parent** at the root item.

![image](https://user-images.githubusercontent.com/54593724/167645994-e5a1e4b2-1287-4406-9d25-9e8a50f84d30.png)

In the photo below, then you can drag the bar to adjust the height to preview the change which can simulate devices with different heights.

![image](https://user-images.githubusercontent.com/54593724/167647258-d633c657-821d-49dd-9a8c-07bb44209fbb.png)

If the component with an image (or background image), you can change the **fill mode** in the style tab at the right inspector.

![image](https://user-images.githubusercontent.com/54593724/167647885-4e54a7dc-dfaf-4ad1-b964-cd4570277490.png)


> adjust the dimensions of each pop-up?
If you enable the **fit parent** mode in the component, and I assume the pop-up is in the middle of the screen.
Then you can pin the pop-up in all directions. (left, right, top, bottom), which means the fixed margin.

![image](https://user-images.githubusercontent.com/54593724/167648645-a8e7b189-31ba-476d-a80f-3b9cee32256a.png)

And the pop-up will resize with the device size, and you can customize the margin by MediaQuery margin.

![image](https://user-images.githubusercontent.com/54593724/167648956-8def80d1-cce0-40f2-a78c-8485441cf11b.png)



Hope the answer addresses your question.

**Comment by MadalinaDrulea** [comment]
Hello,

Thank you for the quick response. In regards to the first part, if I enable the "Fit Parent" option, as you said the width is ok, but I would like the screen to adjust to the height as well, so there is no scrolling on the page (the way google is, for example).

**Comment by px2code** [comment]
@MadalinaDrulea 

Hi, if you set fit parent at the root bottom, the height indeed fits the parent also, and there will no vertical scrolling anymore.
Might you provide your screenshot of the settings? or pxCode link for our investigation if you still have the same problem

**Comment by MadalinaDrulea** [comment]
Hi,

This is the project but I'm not sure if you have access so I add snips below also: https://www.pxcode.io/627a2ce7ad3785001595b8ce/project/627b9c3e7c99d1001313776c/627b9c4ca1bd870014d62956

![image](https://user-images.githubusercontent.com/105295414/167999715-fba223b5-53d1-4438-8791-02344c5eb675.png)
![image](https://user-images.githubusercontent.com/105295414/167999869-7c0d8d41-5bbf-430f-ba4b-74d5ca63e479.png)
![image](https://user-images.githubusercontent.com/105295414/168000186-3ac382a3-7022-4517-84db-0909810ac41e.png)
I did this part in order for the scrolling to disappear.

![image](https://user-images.githubusercontent.com/105295414/168000103-d9d9bdf5-4a95-44ec-9949-1925c14fe3c3.png)
The above is the entire image.

![image](https://user-images.githubusercontent.com/105295414/167999913-b79d4c8e-a8e0-4367-badf-860a55c62375.png)
And in the last image you can see that on the laptop the image is not displayed entirely, it cuts off. On the screen which has a bigger resolution it works fine.

Thank you!

**Comment by px2code** [comment]
I create a similar design to simulate the situation.
And the editing steps are recorded as a video

https://www.loom.com/share/eeb7a273a4aa4de68e63cd636a3a83f0


The major technique here is

- cute **spacers** vertically 
- enable grow and shrink for spacers
- close the min-height

Hope it help.

**Comment by MadalinaDrulea** [comment]
Thank you so much for your time!
